In [10]:
# import tensorflow as tf
import gym
import numpy as np

### Load the environment¶

In [11]:
env = gym.make('FrozenLake-v0')

In [7]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [8]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.674


In [9]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[  2.53142488e-01   1.59651421e-02   2.34330592e-02   2.40590455e-02]
 [  6.86580456e-03   2.02335960e-04   3.67385871e-03   3.58475033e-01]
 [  4.25212010e-03   1.65921918e-02   0.00000000e+00   1.02933866e-01]
 [  4.11276942e-03   0.00000000e+00   0.00000000e+00   4.87082519e-02]
 [  4.91809415e-01   1.70256743e-03   3.44462913e-03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.45974715e-02   6.53855558e-05   1.43948492e-03   1.37716461e-08]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   7.06282687e-03   0.00000000e+00   5.90128157e-01]
 [  0.00000000e+00   5.80932061e-01   0.00000000e+00   1.11517611e-03]
 [  8.66258897e-01   3.97476543e-04   0.00000000e+00   7.18416944e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   8.26602595e-01   0