# Q-Table Learning

In [16]:
import gym
import numpy as np

### Load the environment¶

In [17]:
env = gym.make('FrozenLake-v0')

### Q-Table learning Alg.

In [18]:
#initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
#set learning parameters
lr = .8
y = .95
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #the Q-Table learning algorithm
    while j < 99:
        j+=1
        #choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

In [19]:
print ("Score over time: " +  str(sum(rList)/num_episodes))

Score over time: 0.4725


In [20]:
print("Final Q-Table Values")
print (Q)

Final Q-Table Values
[[8.49604366e-03 7.81819397e-03 8.26964529e-03 1.42873541e-02]
 [1.09855622e-03 1.67532192e-03 2.34066426e-04 3.10401188e-02]
 [6.98345784e-02 4.28474905e-03 4.98728173e-03 4.35296642e-03]
 [2.05096038e-04 1.74235336e-04 1.62962645e-04 4.89924899e-03]
 [9.31854006e-03 2.73022619e-04 1.40827394e-03 2.45160892e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.06313738e-04 1.97376883e-07 3.46048039e-05 1.64328320e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.37363622e-03 5.55570206e-03 4.26163200e-03 3.78128132e-03]
 [5.94581657e-04 1.43341537e-03 5.74222952e-01 9.65566292e-04]
 [3.73022548e-04 5.25798541e-05 0.00000000e+00 1.01493368e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 9.00121625e-01 8.53938260e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 9.97156508e-01]
 [0.00000000e+00 0.00000000e+00 0.